name: Node.js CI

on:
    push:
        branches:
            - next
    pull_request:

jobs:
    build:
        name: Build
        runs-on: ubuntu-latest
        strategy:
            matrix:
                node-version: [20.x]
        steps:
            - name: Install Native Dependencies
              run: |
                  sudo apt-get update
                  sudo apt-get install -y expect-dev

            - name: Checkout
              uses: actions/checkout@v4

            - name: Restore Yarn cache
              uses: actions/cache@v4
              with:
                  path: .yarn/cache
                  key: ${{ runner.os }}-yarn-${{ hashFiles('yarn.lock') }}

            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v4
              with:
                  node-version: ${{ matrix.node-version }}

            - name: Setup Yarn
              run: corepack enable

            - name: Install Yarn Dependencies
              run: |
                  unbuffer yarn install --immutable | tee yarn_output.log
                  if cat yarn_output.log | grep YN0060; then
                    echo "Detected incompatible peer dependencies!"
                    exit 1
                  fi

            - name: Compile
              run: yarn build

    lint:
        name: Run Linter
        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [20.x]

        steps:
            - name: Install Native Dependencies
              run: |
                  sudo apt-get update
                  sudo apt-get install -y expect-dev

            - name: Checkout
              uses: actions/checkout@v4

            - name: Restore Yarn cache
              uses: actions/cache@v4
              with:
                  path: .yarn/cache
                  key: ${{ runner.os }}-yarn-${{ hashFiles('yarn.lock') }}

            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v4
              with:
                  node-version: ${{ matrix.node-version }}

            - name: Setup Yarn
              run: corepack enable

            - name: Install Yarn Dependencies
              run: |
                  unbuffer yarn install --immutable | tee yarn_output.log
                  if cat yarn_output.log | grep YN0060; then
                    echo "Detected incompatible peer dependencies!"
                    exit 1
                  fi

            - name: Run ESLint
              run: yarn eslint "**/*.{js,jsx,ts,tsx}"
