name: "Chromatic"

on:
    push:
        branches:
            - next
            - graphql

jobs:
  chromatic:
    name: Run Chromatic
    runs-on: ubuntu-latest
    strategy:
        matrix:
            node-version: [20.x]
    steps:
        - name: Checkout
          uses: actions/checkout@v4
          with:
            fetch-depth: 0

        - name: Restore Yarn cache
          uses: actions/cache@v4
          with:
              path: .yarn/cache
              key: ${{ runner.os }}-yarn-${{ hashFiles('yarn.lock') }}

        - name: Use Node.js ${{ matrix.node-version }}
          uses: actions/setup-node@v4
          with:
              node-version: ${{ matrix.node-version }}

        - name: Setup Yarn
          run: corepack enable

        - name: Install Dependencies
          run: yarn

        - name: Run Relay
          run: yarn relay

        - name: Run Chromatic
          uses: chromaui/action@latest
          with:
            projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
