name: "Chromatic"

on:
    push:
        branches:
            - next
            - graphql
    workflow_call:
        inputs:
            pull_request_number:
                description: Pull Request Number
                required: true
                type: string

jobs:
    chromatic:
        name: Run Chromatic
        runs-on: ubuntu-latest
        strategy:
            matrix:
                bun-version: [1.2.15]
        steps:
            - name: Checkout
              if: github.event_name == 'push'
              uses: actions/checkout@v4
              with:
                  fetch-depth: 0

            - name: Checkout (PR)
              if: github.event_name != 'push'
              uses: actions/checkout@v4
              with:
                  fetch-depth: 0
                  ref: refs/pull/${{ inputs.pull_request_number }}/head

            - name: Use Bun ${{ matrix.bun-version }}
              uses: oven-sh/setup-bun@v2
              with:
                  bun-version: ${{ matrix.bun-version }}

            - name: Install Dependencies
              run: bun install --frozen-lockfile

            - name: Run Relay
              run: bun run relay-build

            - name: Run Chromatic
              uses: chromaui/action@latest
              with:
                  projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
                  exitOnceUploaded: true
