name: Bun CI

on:
    push:
        branches:
            - next
    pull_request:

jobs:
    build:
        name: Build
        runs-on: ubuntu-latest
        strategy:
            matrix:
                bun-version: [1.2.15]
        steps:
            - name: Install Native Dependencies
              run: |
                  sudo apt-get update
                  sudo apt-get install -y expect-dev

            - name: Checkout
              uses: actions/checkout@v4

            - name: Use Bun ${{ matrix.bun-version }}
              uses: oven-sh/setup-bun@v2
              with:
                  bun-version: ${{ matrix.bun-version }}

            - name: Install Dependencies
              run: bun install --frozen-lockfile

            - name: Compile
              run: bun run build

    lint:
        name: Run Linter
        runs-on: ubuntu-latest

        strategy:
            matrix:
                bun-version: [1.2.15]

        steps:
            - name: Install Native Dependencies
              run: |
                  sudo apt-get update
                  sudo apt-get install -y expect-dev

            - name: Checkout
              uses: actions/checkout@v4

            - name: Use Bun ${{ matrix.bun-version }}
              uses: oven-sh/setup-bun@v2
              with:
                  bun-version: ${{ matrix.bun-version }}

            - name: Install Dependencies
              run: bun install --frozen-lockfile

            - name: Run ESLint
              run: bun eslint "**/*.{js,jsx,ts,tsx}"
